# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rochekey', models.CharField(blank=True, max_length=125, null=True)),
                ('process_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.CharField(blank=True, max_length=255, null=True)),
                ('material_number', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('process_order_creation_date', models.CharField(blank=True, max_length=12, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('process_order_release_date', models.CharField(blank=True, max_length=12, null=True)),
                ('packaging_start_date', models.CharField(blank=True, max_length=12, null=True)),
                ('packaging_end_date', models.CharField(blank=True, max_length=12, null=True)),
                ('packaging_head_pkg_signoff', models.CharField(blank=True, max_length=12, null=True)),
                ('bbr_start', models.CharField(blank=True, max_length=12, null=True)),
                ('bbr_end', models.CharField(blank=True, max_length=12, null=True)),
                ('qa_release_date', models.CharField(blank=True, max_length=12, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_status', models.IntegerField(blank=True, null=True)),
                ('po_create_release', models.IntegerField(blank=True, null=True)),
                ('release_to_pkg_start', models.IntegerField(blank=True, null=True)),
                ('pkg_start_bbr_finish', models.IntegerField(blank=True, null=True)),
                ('pkg_finish_begin', models.IntegerField(blank=True, null=True)),
                ('brr_start_finish', models.IntegerField(blank=True, null=True)),
                ('brr_finish_qp_release', models.IntegerField(blank=True, null=True)),
                ('fge2e', models.IntegerField(blank=True, null=True)),
                ('check_column', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RocheNewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rochekey', models.CharField(blank=True, db_column='Key', max_length=18, null=True)),
                ('process_order_number', models.IntegerField(blank=True, null=True)),
                ('order_type_packaging_or_repackaging_field', models.CharField(blank=True, max_length=4, null=True)),
                ('material_number', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=40, null=True)),
                ('process_order_creation_date', models.CharField(blank=True, max_length=9, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=10, null=True)),
                ('process_order_release_date', models.CharField(blank=True, max_length=9, null=True)),
                ('packaging_line_start', models.CharField(blank=True, max_length=9, null=True)),
                ('packaging_line_finish', models.CharField(blank=True, max_length=9, null=True)),
                ('packaging_final_check_date', models.CharField(blank=True, max_length=9, null=True)),
                ('brr_start_date', models.CharField(blank=True, max_length=9, null=True)),
                ('brr_end_date', models.CharField(blank=True, max_length=9, null=True)),
                ('qa_release_date', models.CharField(blank=True, max_length=9, null=True)),
                ('product', models.CharField(blank=True, max_length=12, null=True)),
                ('batch_status', models.CharField(blank=True, max_length=4, null=True)),
                ('po_create_to_po_release', models.IntegerField(blank=True, null=True)),
                ('po_release_to_pkg_start', models.IntegerField(blank=True, null=True)),
                ('pkg_start_to_pkg_finish', models.IntegerField(blank=True, null=True)),
                ('pkg_finish_to_pkg_final_check', models.CharField(blank=True, max_length=5, null=True)),
                ('pkg_final_check_to_brr_begin', models.CharField(blank=True, max_length=4, null=True)),
                ('brr_begin_to_brr_finish', models.CharField(blank=True, max_length=4, null=True)),
                ('brr_finish_to_qp_release', models.CharField(blank=True, max_length=5, null=True)),
                ('fg_e2e', models.CharField(blank=True, max_length=5, null=True)),
                ('check_column', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
