# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pivot_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=15)),
                ('PO_Crearte_to_Release', models.FloatField(default=0.0)),
                ('Pkg_Start_to_Finish', models.FloatField(default=0.0)),
                ('Release_to_Pkg_Start', models.FloatField(default=0.0)),
                ('BRR_Start_To_Finish', models.FloatField(default=0.0)),
                ('BRR_Finish_to_QP_Release', models.FloatField(default=0.0)),
            ],
        ),
    ]
