# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rochekey', models.CharField(blank=True, max_length=125, null=True)),
                ('process_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('order_type', models.CharField(blank=True, max_length=255, null=True)),
                ('material_number', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('process_order_creation_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('process_order_release_date', models.DateTimeField(blank=True, null=True)),
                ('packaging_start_date', models.DateField(blank=True, null=True)),
                ('packaging_end_date', models.DateField(blank=True, null=True)),
                ('packaging_head_pkg_signoff', models.DateField(blank=True, null=True)),
                ('bbr_start', models.DateField(blank=True, null=True)),
                ('bbr_end', models.DateField(blank=True, null=True)),
                ('qa_release_date', models.DateField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_status', models.IntegerField(blank=True, null=True)),
                ('po_create_release', models.IntegerField(blank=True, null=True)),
                ('release_to_pkg_start', models.IntegerField(blank=True, null=True)),
                ('pkg_start_bbr_finish', models.IntegerField(blank=True, null=True)),
                ('pkg_finish_begin', models.IntegerField(blank=True, null=True)),
                ('brr_start_finish', models.IntegerField(blank=True, null=True)),
                ('brr_finish_qp_release', models.IntegerField(blank=True, null=True)),
                ('fge2e', models.IntegerField(blank=True, null=True)),
                ('check_column', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pivot_table',
        ),
    ]
