# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-14 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('login_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('logout_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
