# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-24 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rochenewmodel',
            old_name='rochekey',
            new_name='rocheid',
        ),
    ]
