# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0002_logindetails_userauthentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('authorized', models.CharField(default='FALSEe', max_length=10)),
            ],
        ),
    ]
