# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roche_app', '0003_userauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='authorized',
            field=models.CharField(default='FALSE', max_length=10),
        ),
    ]
