# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-17 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleSignInApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivot_table',
            name='BRR_Finish_to_QP_Release',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pivot_table',
            name='BRR_Start_To_Finish',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pivot_table',
            name='PO_Crearte_to_Release',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pivot_table',
            name='Pkg_Start_to_Finish',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pivot_table',
            name='Release_to_Pkg_Start',
            field=models.FloatField(default=0.0),
        ),
    ]
