"""
Django settings for GoogleSignin project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l!^q^cfm5hjp4fui780!*^(r27-2p%7)os0pj*z#n*yv8&*a19'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.0.108:8000','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'roche_app',
    'social.apps.django_app.default',
    'bootstrap3',
    'whitenoise.runserver_nostatic',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'GoogleSignin.urls'

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
            'debug': DEBUG,
        },
    },
]

WSGI_APPLICATION = 'GoogleSignin.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'social.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]


DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            'NAME': 'ebdb',
            'USER': 'root',
            'PASSWORD': 'mysql123',
            'HOST': 'aa17zrjytsb1e8p.c4ubrs2xpbu6.ap-south-1.rds.amazonaws.com',
            'PORT': '3306',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = ['https://felt-development.yqxmcpqanb.ap-south-1.elasticbeanstalk.com/complete/google-oauth2/','http://felt-development.yqxmcpqanb.ap-south-1.elasticbeanstalk.com/complete/google-oauth2/','http://felt-env.k9yhtfp9dg.ap-south-1.elasticbeanstalk.com/complete/google-oauth2/','https://felt-env.k9yhtfp9dg.ap-south-1.elasticbeanstalk.com/complete/google-oauth2/','http://127.0.0.1:8000/complete/google-oauth2/' , 'https://serene-reef-39478.herokuapp.com/complete/google-oauth2/', 'http://serene-reef-39478.herokuapp.com/complete/google-oauth2/']
SOCIAL_AUTH_LOGIN_ERROR_URL = '/'
#SOCIAL_AUTH_REDIRECT_IS_HTTPS = True


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '760665739517-8on96qc4f61e3u6g79vgieq7fi34a5oi'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'kZhdJvWgDxpG1LJRbqrLwUsT'